"use client";

import { useState } from "react";
import { Download, Check, Loader2 } from "lucide-react";
import { BrandProject } from "@/types";

interface ExportBrandKitProps {
  project: BrandProject;
}

function generateMarkdown(project: BrandProject): string {
  const d = project.discover_data;
  const p = project.position_data;
  const s = project.shape_data;
  const v = project.visualize_data;
  const c = project.challenge_data;
  const del = project.deliver_data;

  const lines: string[] = [];

  lines.push(`# ${project.title} — Brand Intelligence Kit`);
  lines.push(`> Generated by BrandOS · ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  // Stage 1
  if (d) {
    lines.push(`## Stage 1: Discovery`);
    lines.push(``);
    lines.push(`**Problem Statement**`);
    lines.push(`> ${d.problemStatement}`);
    lines.push(``);
    lines.push(`**Primary Value Hook**`);
    lines.push(`> ${d.primaryValueHook}`);
    lines.push(``);
    lines.push(`### Target Audience`);
    lines.push(`- **Segment**: ${d.targetAudience.primarySegment}`);
    lines.push(`- **Demographics**: ${d.targetAudience.demographics}`);
    lines.push(`- **Psychographics**: ${d.targetAudience.psychographics}`);
    lines.push(``);
    lines.push(`**Core Motivations**`);
    d.targetAudience.coreMotivations.forEach((m) => lines.push(`- ${m}`));
    lines.push(``);
    lines.push(`**Acute Pain Points**`);
    d.targetAudience.acutePainPoints.forEach((p) => lines.push(`- ${p}`));
    lines.push(``);
    lines.push(`**Key Constraints**`);
    d.keyConstraints.forEach((k) => lines.push(`- ${k}`));
    lines.push(``);
    lines.push(`---`);
    lines.push(``);
  }

  // Stage 2
  if (p) {
    lines.push(`## Stage 2: Positioning`);
    lines.push(``);
    lines.push(`**Positioning Statement**`);
    lines.push(`> ${p.positioningStatement}`);
    lines.push(``);
    lines.push(`| Field | Value |`);
    lines.push(`|-------|-------|`);
    lines.push(`| Market Category | ${p.marketCategory} |`);
    lines.push(`| Core Differentiator | ${p.coreDifferentiator} |`);
    lines.push(`| Value Proposition | ${p.valueProposition} |`);
    lines.push(`| Competitor Type | ${p.competitiveAngle.primaryCompetitorType} |`);
    lines.push(`| Unique Angle | ${p.competitiveAngle.uniqueAngle} |`);
    lines.push(``);
    lines.push(`---`);
    lines.push(``);
  }

  // Stage 3
  if (s) {
    lines.push(`## Stage 3: Brand Identity & Voice`);
    lines.push(``);
    lines.push(`**Selected Brand Name**: ${s.selectedName}`);
    lines.push(`**Tagline**: "${s.selectedTagline}"`);
    lines.push(``);
    lines.push(`### Naming Territories`);
    lines.push(``);
    s.namingTerritories.forEach((n) => {
      lines.push(`**${n.name}** _(${n.category})_ · Memorability: ${n.memorabilityScore}/10`);
      lines.push(`> ${n.rationale}`);
      lines.push(`> Domain concept: \`${n.domainConcept}\``);
      lines.push(``);
    });
    lines.push(`### Brand Voice`);
    lines.push(``);
    lines.push(`**Tone Descriptors**: ${s.brandVoice.toneDescriptors.join(", ")}`);
    lines.push(``);
    lines.push(`**Traits to Embody**`);
    s.brandVoice.traitsToEmbody.forEach((t) => {
      lines.push(`- **${t.trait}**: ${t.justification}`);
      lines.push(`  > _"${t.behavioralExample}"_`);
    });
    lines.push(``);
    lines.push(`**Traits to Avoid**`);
    s.brandVoice.traitsToAvoid.forEach((a) => lines.push(`- ✕ ${a}`));
    lines.push(``);
    lines.push(`**Messaging Pillars**`);
    s.messagingPillars.forEach((mp) => {
      lines.push(`- **${mp.pillar}**: ${mp.description}`);
    });
    lines.push(``);
    lines.push(`---`);
    lines.push(``);
  }

  // Stage 4
  if (v) {
    lines.push(`## Stage 4: Visual Design Brief`);
    lines.push(``);
    lines.push(`**Composition Style**: ${v.compositionStyle}`);
    lines.push(``);
    lines.push(`### Color Palette`);
    lines.push(``);
    lines.push(`| Name | Hex | Role | Association |`);
    lines.push(`|------|-----|------|-------------|`);
    v.colorPalette.forEach((c) => {
      lines.push(`| ${c.name} | \`${c.hex}\` | ${c.usageRole} | ${c.emotionalAssociation} |`);
    });
    lines.push(``);
    lines.push(`### Typography`);
    lines.push(`- **Heading**: ${v.typography.headingFont} (fallback: ${v.typography.headingFallback})`);
    lines.push(`- **Body**: ${v.typography.bodyFont} (fallback: ${v.typography.bodyFallback})`);
    lines.push(`- **Rationale**: ${v.typography.pairingRationale}`);
    lines.push(``);
    lines.push(`### Logo & Symbol Concepts`);
    v.logoAndSymbolConcepts.forEach((l) => lines.push(`- ✦ ${l}`));
    lines.push(``);
    lines.push(`### Visual Concepts to Avoid`);
    v.visualConceptsToAvoid.forEach((a) => lines.push(`- ✕ ${a}`));
    lines.push(``);
    lines.push(`---`);
    lines.push(``);
  }

  // Stage 5
  if (c) {
    lines.push(`## Stage 5: Gemini Adversarial Audit`);
    lines.push(``);
    lines.push(`**Overall Cohesion Score**: ${c.overallCohesionScore}/100`);
    lines.push(`**Validation Status**: ${c.passedValidation ? "✅ PASSED" : "⚠️ REVISIONS NEEDED"}`);
    lines.push(`**Verdict**: ${c.verdictSummary}`);
    lines.push(``);
    if (c.critiqueItems.length > 0) {
      lines.push(`### Detected Flags`);
      c.critiqueItems.forEach((item) => {
        lines.push(`**[${item.severity.toUpperCase()}] ${item.id} — ${item.category.replace("_", " ")}**`);
        lines.push(`> ${item.description}`);
        lines.push(`> 🔧 Remedy: ${item.actionableRemedy}`);
        lines.push(``);
      });
    }
    lines.push(`---`);
    lines.push(``);
  }

  // Stage 6
  if (del) {
    lines.push(`## Stage 6: Launch Kit`);
    lines.push(``);
    lines.push(`**One-Line Pitch**`);
    lines.push(`> ${del.oneLinePitch}`);
    lines.push(``);
    lines.push(`**Elevator Pitch**`);
    lines.push(`> ${del.elevatorPitch}`);
    lines.push(``);
    lines.push(`### Landing Page Hero`);
    lines.push(`- **Headline**: ${del.landingPageHero.headline}`);
    lines.push(`- **Subheadline**: ${del.landingPageHero.subheadline}`);
    lines.push(`- **Primary CTA**: ${del.landingPageHero.primaryCtaText}`);
    if (del.landingPageHero.secondaryCtaText) {
      lines.push(`- **Secondary CTA**: ${del.landingPageHero.secondaryCtaText}`);
    }
    lines.push(``);
    lines.push(`### Social Launch Posts`);
    del.launchSocialPosts.forEach((post) => {
      lines.push(`#### ${post.platform.replace("_", " ").toUpperCase()}`);
      lines.push(`**Hook**: ${post.hook}`);
      lines.push(``);
      lines.push(post.body);
      lines.push(``);
      lines.push(`**CTA**: ${post.callToAction}`);
      lines.push(``);
    });
    lines.push(`### Brand Guardrails`);
    del.brandGuardrails.forEach((g) => {
      lines.push(`- ⚠️ **${g.rule}**: ${g.whyItMatters}`);
    });
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`_Generated by BrandOS — AI-Powered Brand Intelligence System_`);

  return lines.join("\n");
}

export default function ExportBrandKit({ project }: ExportBrandKitProps) {
  const [isExporting, setIsExporting] = useState(false);
  const [done, setDone] = useState(false);

  const hasAnyData =
    project.discover_data ||
    project.position_data ||
    project.shape_data ||
    project.visualize_data ||
    project.challenge_data ||
    project.deliver_data;

  const handleExport = async () => {
    if (!hasAnyData) return;
    setIsExporting(true);

    await new Promise((r) => setTimeout(r, 600)); // brief visual feedback

    const markdown = generateMarkdown(project);
    const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${project.title.replace(/[^a-z0-9]/gi, "_").toLowerCase()}_brand_kit.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setIsExporting(false);
    setDone(true);
    setTimeout(() => setDone(false), 2500);
  };

  return (
    <button
      onClick={handleExport}
      disabled={!hasAnyData || isExporting}
      title={!hasAnyData ? "Complete at least Stage 1 to export" : "Download Brand Kit as Markdown"}
      className={`text-xs px-3 py-1.5 rounded-lg border transition flex items-center gap-1.5 disabled:cursor-not-allowed ${
        done
          ? "bg-emerald-500/15 text-emerald-400 border-emerald-500/30"
          : hasAnyData
          ? "bg-white/5 text-slate-200 border-white/10 hover:bg-white/10 hover:text-white"
          : "bg-white/5 text-slate-600 border-white/10"
      }`}
    >
      {isExporting ? (
        <Loader2 className="w-3.5 h-3.5 animate-spin" />
      ) : done ? (
        <Check className="w-3.5 h-3.5" />
      ) : (
        <Download className="w-3.5 h-3.5" />
      )}
      {done ? "Downloaded!" : "Export Brand Kit"}
    </button>
  );
}
